### ISSUE TITLE
API for public holidays

### ISSUE THREAD

**Issue by michischeid** [WISEA12/backend#122]

**Comment by tarekauel** [comment]
@michischeid please check output of #125

**Comment by LarsTi** [comment]
Problems with backend:
Prototype seems to be overwritten

**Comment by tarekauel** [comment]
fixed with  18dbe23

**Comment by michischeid** [comment]
looks good. thanks. Can you add API description to the Schnittstellen doc, please.

**Comment by tarekauel** [comment]
done
