### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by LarsTi** [WISEA12/backend#124]
Give an API for POST PUT DELETE GET
GET only shows user name
POST creates new user
    {"username":"string", 
     "Passwort" : "hashedString"}
PUT changes user
    {"username":"string",
     "Passwort" : "hashedString"}
DELETE deletes user
    /api/users/:username

POST api for password verification
{"username":"string",
"Passwort" : "hashedString"}

**Comment by tarekauel** [comment]
hash is not a good idea without salt, because of privacy issues. (Maybe someone can extract their passwords and they may use it for multiple services)

```json

GET: for check if user / password is valid
/users/:username/:password
RESPONSE: status 200: (typically, you'd get a token, but we don't have a real usermanagement)
  {
    "success": true
  }
RESPONSE: status 400:
  {
    "success": false
  }

GET: salt
/users/:username
RESPONSE status 200
  {
    "salt": "salt"
  }
RESPONSE status 404 (is a security issue, but we don't care!) 

PUT: change password
/users/:username
REQUEST: 
  {
    "password": "hashedPassword"
  }
RESPONSE: 200

POST: create user
/users
REQUEST
  {
    "username": "username",
    "salt": "salt",
    "password": "password"
  }

DELETE: 
/users/:username
```
@michischeid is it easy for you to integrate a real user management. We can easily add a middleware in the backend and check for a session token as cookie. Can you integrate it easily, too?

**Comment by michischeid** [comment]
This is definitely the better solution and should be ok for us. Nevertheless we should agree on a hashing algorithm.

**Comment by michischeid** [comment]
@treyla  Lars Trey will be the responsible person for this functionality in the frontend

**Comment by michischeid** [comment]
@tarekauel Can you please add the API description to the schnittstellen doc

**Comment by tarekauel** [comment]
done
