### ISSUE TITLE
collision detection API

### ISSUE THREAD

**Issue by michischeid** [WISEA12/backend#127]
POST:
 - Request: {
   events: ["eventObject"{}]
   }
 
- Response:
{
  "validEvents": [
    {
      "eventsObject": {}
    }
  ],
  "collidingEvents": [
    {
      "newEvent": {
        "eventObject": {}
      },
      "collidingWithTitle":""
    }
  ]
}

**Comment by tarekauel** [comment]
POST is not the correct method:

Get:
```url
/events/checkEvents?events=[eventObject1, eventObject2]
```

Response
```javascript
{
  "validEvents": [eventObject1,...],
  "collidingEvents": [ [existingEvent, eventObject1], ...]
}
```

EventObject
```json
{
  "title": "Title",
  "startDate": "date",
  "endDate": "date",
}
```

Which `date`format do you prefer?

**Comment by michischeid** [comment]
The Standard iso String which  we have at events

Looks good

**Comment by michischeid** [comment]
the eventObject should be a normal eventObject (schnittstellen doc) not just {
  "title": "Title",
  "startDate": "date",
  "endDate": "date",
}

**Comment by LarsTi** [comment]
date, lecture, semester are already in check.
commit:
406f29aea162ded5ac97236c0eed4a94a49102f2

**Comment by LarsTi** [comment]
collision detection w/o public holidays.

**Comment by LarsTi** [comment]
implemented

**Comment by felixkam93** [comment]
Wenn ein Objekt bereits besteht, und es durch drag&drop (um bspw 30 min) verschoben wird im Kalender, meldet die CollisionDetection, dass es einen Konflikt zwischen den beiden Events gibt. Ich gehe mal davon aus, dass so etwas wie eine überprüfung, ob es sich bei der Überschneidung um ein und die selben Events handelt noch fehlt. 
Falls die Fehlerbeschreibung nicht eindeutig ist hänge ich gerne noch screenshots an.

**Comment by felixkam93** [comment]
Darüber hinaus wird, wenn es sich bei dem Event um eine Klausur handelt, das "isExam" Flag einfach nicht wieder mit zurück geliefert -> Nach Überprüfung ist das Klausur Event keine Klausur mehr.

**Comment by LarsTi** [comment]
Zu deinem ersten Problem:
Das teil war auf der DB gespeichert. Also kriegst du logischerweise beim verschieben nen error.
Kannst du auch gut abfangen, wenn du dir die ID anguckst. Eigentlich kannst du dir das mal in den colliding events anschauen.

Zu deinem zweiten:
Ungewöhnlich, schaue ich mir mal an.. ;)

**Comment by felixkam93** [comment]
okay @LarsTi also soll ich das im Frontend jedes mal prüfen?

**Comment by LarsTi** [comment]
Naja, es ist ja eine collision, aber ich kann das nachher auch machen..
Musst mir nur sagen

**Comment by LarsTi** [comment]
Der zweite Fehler (isExam flag ändert sich) tritt bei mir nicht auf.
Bitte jeden fehler als eigenen issue aufmachen, damit wir die fehler nachverfolgen können und nicht in einem issue 5 fehler behandelt werden.
