### ISSUE TITLE
Delet Modul is pending

### ISSUE THREAD

**Issue by fischermax** [WISEA12/backend#135]
Delete of a Modul is pending; tested with frontend ( latest commit e3a8579c00) and backend ( latest commit 114d126933) and cleared database
![deletemodul](https://cloud.githubusercontent.com/assets/8883870/6807199/4e10b720-d24d-11e4-831e-2966e0d6f4bc.jpg)

**Comment by LarsTi** [comment]
Of course, if you dont use the api like specified.
look at schnittstellen document line 100 how to use delete on module.
