### ISSUE TITLE
Löschen des Modulplans (NICHT) zulassen

### ISSUE THREAD

**Issue by felixkam93** [WISEA12/backend#141]
Ein Modulplan darf gelöscht werden, solange kein Kurs dem Modulplan folgt (Fehlermeldung: Ein Kurs folgt diesem Modulplan bla bla bla ...)
Ein Modulplan kann momentan NICHT gelöscht werden, wenn noch Module mit ihm verbunden sind. Dies sollte aber möglich sein.

**Comment by LarsTi** [comment]
#143
