### ISSUE TITLE
Fehlermeldungen

### ISSUE THREAD

**Issue by michischeid** [WISEA12/backend#144]
Vielleicht sollten wir uns noch etwas überlegen, wie man die Fehlermedlungen benutzerfreundlich machen kann. Zumindest die, die öfters vorkommen, wie z.B. ... has edges in graph. Ich finde man sollte hier "... hat Beziehungen zu anderen Objekten und kann daher nicht gelöscht werden" ausgeben.  Was ist eure Meinung?

**Comment by LarsTi** [comment]
Das ist mir im Prinzip egal, nur dann brauchen wir ne eindeutige Aussage, welcher Fehlertext wann kommen soll.

**Comment by felixkam93** [comment]
Denkt ihr es muss eine "Fehlermeldung" erscheinen, wenn man die Termine eines speziellen Dozenten im Kalender anzeigen will, aber er keine Termine für den Zeitraum des Semesters hat? Sprich das Antwort Array [] ist?

**Comment by LarsTi** [comment]
Gibt das backend dir ne Fehlermeldung?
sollte eigentlich einfach nur ein leerer response sein.

**Comment by felixkam93** [comment]
ja genau ist leer, also meinst du es ist eher front end sache das eben abzuprüfen und dann eventuell n pop up zu zeigen?

**Comment by LarsTi** [comment]
@michischeid 
@treyla 
@felixkam93 

noch relevant?

**Comment by LarsTi** [comment]
@michischeid 
@treyla 
@felixkam93
