### ISSUE TITLE
"Fehler im Backend" bei Kursplanung

### ISSUE THREAD

**Issue by NessiT** [WISEA12/backend#145]
Kursplanung:
Wenn ich in einer Kachel auf ein hinzugefügtes Modul klicke, erscheint bei mir die Fehlermeldung "Fehler im Backend".
Danach werden auch alle eingefügten Module beim Neuladen aus der Kursplanung entfernt.

**Comment by LarsTi** [comment]
Ist ne frontend sache, aber klingt trotzdem komisch..^^
