### ISSUE TITLE
Ladezeit für get auf /api/course

### ISSUE THREAD

**Issue by felixkam93** [WISEA12/backend#149]
Dauert auch mal gerne 10 sekunden :D hier ist die curl falls ihr die braucht:
curl "http://localhost:8080/api/course" -H 
"Accept-Encoding: gzip, deflate, sdch" -H 
"Accept-Language: en-US,en;q=0.8,de;q=0.6" -H 
"User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36" -H 
"Accept: application/json, text/plain, */*" -H 
"Referer: http://localhost:8080/" -H 
"If-None-Match: W/""3tTD7GJlK7RM33aB3BEAeA==""" -H 
"Connection: keep-alive" --compressed

**Comment by LarsTi** [comment]
1 sekunde = 89 items geladen.
machts zur not wie beim dozenten und ladet erst einen teil der course (10 - 20) und dann den rest?

**Comment by LarsTi** [comment]
PS: assignee ist daniel, der hat das programmiert

**Comment by felixkam93** [comment]
okay sorry ... ich muss zugeben es ist immer anders -,- 
mal habe ich das problem, mal nicht ... michael sagte er hätte es auch schon gehabt

**Comment by LarsTi** [comment]
#161
