### ISSUE TITLE
Die Beschreibung beim Anlegen Modulplans ist nicht required

### ISSUE THREAD

**Issue by npartsch** [WISEA12/backend#153]
Das Feld Beschreibung ist kein required field. 
Fehlermeldung beim Anlegen eines Modulplans:
Required fields are not filled: ["description"]

**Comment by tarekauel** [comment]
Url: (POST) 
```
http://localhost:8080/api/moduleplan
```
Body
``` 
```
Response
```json
{
  "id": 2
}
```
Status ```CREATED 201```
