### ISSUE TITLE
Kann nicht gleiches Modul für unterschiedliche Modulpläne anlegen

### ISSUE THREAD

**Issue by fischermax** [WISEA12/backend#155]
Wollte das Modul "Grundlagen der Rechnungslegung" mit "FiBu" und "KLR" einmal für SE und einmal für AM anlegen. AM ging nicht, da das Modul bereits für SE existiert!! --> So lassen sich die Modulpläne nicht abbilden, da einige Module in allen Vertiefungsrichtungen vorkommen

**Comment by tarekauel** [comment]
natürlich nicht. Ein Modul ist UNABHÄNGIG von einem modulplan. (siehe API) ein modul wird über den Namen identifiziert. Daher DARF das nicht möglich sein. 

Wenn zwei Module IDENTISCH sind können sie an zwei unterschiedlichen modulplänen hängen, wenn nicht, müssen sie UNTERSCHIEDLICHE namen haben.

**Comment by fischermax** [comment]
Schau dir bitte mal die Modulpläne für SE und AM an:
http://www.am.dhbw-mannheim.de/fileadmin/ms/wi/dl_am/Studiengangsbeschreibung_WI-AM.pdf (S.3)
http://www.se.dhbw-mannheim.de/fileadmin/ms/wi/dl_swm/modulkatalog-dhbw-wi-se-ab-2011-version-2012-11-05.pdf (S.2)

Da gibts beides mal das Modul "Grundlagen der Rechnungslegung" mit den Vorlesungen FiBu und KLR, sowie jeweils 36 Stunden und 6 CPs.

Warum kann ich das an Modulplan SE und nicht auch an AM hängne, obwohl du ja oben geschrieben hast, dass das gehen muss

**Comment by tarekauel** [comment]
"natürlich nicht. Ein Modul ist UNABHÄNGIG von einem modulplan. (siehe API) ein modul wird über den Namen identifiziert. Daher DARF das nicht möglich sein.

Wenn zwei Module IDENTISCH sind können sie an zwei unterschiedlichen modulplänen hängen, wenn nicht, müssen sie UNTERSCHIEDLICHE namen haben.

(P.s. den ersten Fall gibt das UI nicht her)"

P.s.: der erste Fall ist zwei Module sind identisch. Hab es ausprobiert. Per put auf ModulePlan kann man ein Modul hinzufügen, das bisher nur an einem anderen hängt.

Also das UI gibt das nicht her! Module müssen einen eindeutigen Namen haben. Anwender könnten später das Jahr anhängen, wenn ein Modul gleich heißen soll, aber unterschiedlich ist
