### ISSUE TITLE
collision

### ISSUE THREAD

**Issue by fischermax** [WISEA12/backend#162]
curl "http://localhost:8080/api/events/checkEvents?events="%"5B"%"7B"%"22docent"%"22:"%"7B"%"22firstName"%"22:"%"22Armin"%"22,"%"22lastName"%"22:"%"22Wiedemann"%"22,"%"22sex"%"22:"%"22m"%"22,"%"22employer"%"22:"%"22DHBW+Mannheim"%"22,"%"22state"%"22:"%"22new"%"22,"%"22email"%"22:"%"22armin.wiedemann@dhbw-mannheim.de"%"22,"%"22id"%"22:6,"%"22title"%"22:"%"22Prof.+Dr."%"22,"%"22lectures"%"22:"%"5B"%"7B"%"22shortTitle"%"22:"%"22Logik"%"22,"%"22title"%"22:"%"22Logik+und+Algebra"%"22"%"7D,"%"7B"%"22shortTitle"%"22:"%"22Statistik"%"22,"%"22title"%"22:"%"22Statistik"%"22"%"7D,"%"7B"%"22shortTitle"%"22:"%"22MuW+SE"%"22,"%"22title"%"22:"%"22Methoden+und+Werkzeuge+des+Software-Engineering"%"22"%"7D"%"5D,"%"22name"%"22:"%"22Prof.+Dr.+Armin+Wiedemann"%"22"%"7D,"%"22lecture"%"22:"%"7B"%"22shortTitle"%"22:"%"22MuW+SE"%"22,"%"22title"%"22:"%"22Methoden+und+Werkzeuge+des+Software-Engineering"%"22"%"7D,"%"22title"%"22:"%"22MuW+SE+"%"5CnWiedemann"%"22,"%"22room"%"22:"%"7B"%"22number"%"22:"%"22240B"%"22,"%"22id"%"22:1,"%"22course"%"22:"%"5B"%"5D"%"7D,"%"22plannedHours"%"22:2.25,"%"22pause"%"22:15,"%"22semester"%"22:"%"7B"%"22number"%"22:1,"%"22id"%"22:1,"%"22lecture"%"22:"%"5B"%"7B"%"22hours"%"22:33,"%"22lecture"%"22:"%"7B"%"22shortTitle"%"22:"%"22Spezial2"%"22,"%"22title"%"22:"%"22Standortspezifische+Lehreinheit+2"%"22,"%"22openHours"%"22:33"%"7D,"%"22openHours"%"22:33"%"7D,"%"7B"%"22hours"%"22:33,"%"22lecture"%"22:"%"7B"%"22shortTitle"%"22:"%"22MuW+SE"%"22,"%"22title"%"22:"%"22Methoden+und+Werkzeuge+des+Software-Engineering"%"22,"%"22openHours"%"22:33"%"7D,"%"22openHours"%"22:33"%"7D,"%"7B"%"22hours"%"22:30,"%"22lecture"%"22:"%"7B"%"22shortTitle"%"22:"%"22Themen+SE"%"22,"%"22title"%"22:"%"22Ausgew"%"C3"%"A4hlte+Themen+des+Software-Engineering"%"22,"%"22openHours"%"22:30"%"7D,"%"22openHours"%"22:30"%"7D,"%"7B"%"22hours"%"22:30,"%"22lecture"%"22:"%"7B"%"22shortTitle"%"22:"%"22Spezial3"%"22,"%"22title"%"22:"%"22Standortspezifische+Lehreinheit+3"%"22,"%"22openHours"%"22:30"%"7D,"%"22openHours"%"22:30"%"7D,"%"7B"%"22hours"%"22:33,"%"22lecture"%"22:"%"7B"%"22shortTitle"%"22:"%"22UI-Entw."%"22,"%"22title"%"22:"%"22Webbasierte+Datenbankanwendungen+bzw.+User-Interface-Entwicklung+und+Usability"%"22,"%"22openHours"%"22:33"%"7D,"%"22openHours"%"22:33"%"7D,"%"7B"%"22hours"%"22:28,"%"22lecture"%"22:"%"7B"%"22shortTitle"%"22:"%"22SQ3"%"22,"%"22title"%"22:"%"22Schl"%"C3"%"BCsselqualifikationen+3"%"22,"%"22openHours"%"22:28"%"7D,"%"22openHours"%"22:28"%"7D"%"5D,"%"22startDate"%"22:"%"222015-04-07T10:22:25.943Z"%"22,"%"22endDate"%"22:"%"222015-04-07T10:22:25.943Z"%"22"%"7D,"%"22start"%"22:"%"222015-04-21T07:00:00.000Z"%"22,"%"22end"%"22:"%"222015-04-21T10:00:00.000Z"%"22"%"7D"%"5D" -H "Pragma: no-cache" -H "Accept-Encoding: gzip, deflate, sdch" -H "Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36" -H "Accept: application/json, text/plain, */*" -H "Referer: http://localhost:8080/" -H "Connection: keep-alive" -H "Cache-Control: no-cache" --compressed

**Comment by LarsTi** [comment]
aa9e69a2102119671a4f2b4024aa4b0c48395849

**Comment by LarsTi** [comment]
#174
