### ISSUE TITLE
Vorlesungsplan verschönern

### ISSUE THREAD

**Issue by michischeid** [WISEA12/backend#190]
Der Vorlesungsplan sollte noch etwas verschönert werden.
@treyla kann hier bestimmt ein paar Ideen einbringen

**Comment by LarsTi** [comment]
[Bild der anderen Gruppe](https://cloud.githubusercontent.com/assets/4633382/7155025/ab7cd49c-e35b-11e4-8260-1ea2e776f141.jpg)
[Frontend Issue](https://github.com/WISEA12/frontend/issues/130)

**Comment by LarsTi** [comment]
@michischeid @treyla schauts euch bitte noch mal an..^^
