### ISSUE TITLE
PUT course - Kurs ändern: 500 Internal ServerError

### ISSUE THREAD

**Issue by michischeid** [WISEA12/backend#191]
curl "http://localhost:8080/api/course/1" -X PUT -H "Pragma: no-cache" -H "Origin: http://localhost:8080" -H "Accept-Encoding: gzip, deflate, sdch" -H "Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "User-Agent: Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36" -H "Content-Type: application/json;charset=UTF-8" -H "Accept: application/json, text/plain, */*" -H "Cache-Control: no-cache" -H "Referer: http://localhost:8080/" -H "Cookie: user=vvs" -H "Connection: keep-alive" --data-binary "{""name"":""WWI12SEA"",""id"":1,""semester"":[{""endDate"":""2015-04-13T11:11:49.150Z"",""startDate"":""2015-01-31T23:00:00.000Z"",""number"":1,""id"":1,""lecture"":[{""hours"":5,""lecture"":{""title"":""Fortgeschrittene Programmierung"",""shortTitle"":""PROG II""}},{""hours"":4,""lecture"":{""title"":""Programmierung I"",""shortTitle"":""Programmierun""}},{""hours"":5,""lecture"":{""title"":""Mathematik für Wirtschaftsinformatiker"",""shortTitle"":""Mathe WI""}},{""hours"":2,""lecture"":{""title"":""Einführung in die Betriebswirtschaftslehre"",""shortTitle"":""Einf. BWL""}},{""hours"":3,""lecture"":{""title"":""Grundlagen der allgemeinen Betriebswirtschaftslehre"",""shortTitle"":""Grundlagen BW""}}]},{""number"":2,""id"":2,""lecture"":[]},{""number"":3,""id"":3,""lecture"":[]},{""number"":4,""id"":4,""lecture"":[]},{""number"":5,""id"":5,""lecture"":[]},{""number"":6,""id"":6,""lecture"":[]}],""studyManager"":[{""studyProgramManager"":true,""state"":""new"",""title"":""Prof. Dr.-Ing."",""street"":""Langgässerweg 4"",""firstName"":""Jörg"",""lastName"":""Baumgart"",""sex"":""m"",""zipCode"":""64285"",""phonePrivate"":""06151 61327"",""city"":""Darmstadt"",""id"":21,""lectures"":[{""title"":""Wissenschaftliches Arbeiten III"",""shortTitle"":""wiss. Arb III""}],""name"":""Prof. Dr.-Ing. Jörg Baumgart""}],""modulePlan"":[{""name"":""WWI12SE"",""id"":1}],""room"":[{""name"":""240B"",""number"":""240B"",""id"":68}]}" --compressed

**Comment by LarsTi** [comment]
error status 500 weist auf nen db oder cypher fehler hin, ich habe das problem bei mir leider nicht reproduzieren können. 
kannst du mal schritt für schritt posten, wie das problem auftritt?
