### ISSUE TITLE
POST course --> Response enthält keinen Raum

### ISSUE THREAD

**Issue by michischeid** [WISEA12/backend#192]
curl "http://localhost:8080/api/course" -H "Pragma: no-cache" -H "Origin: http://localhost:8080" -H "Accept-Encoding: gzip, deflate" -H "Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "User-Agent: Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36" -H "Content-Type: application/json;charset=UTF-8" -H "Accept: application/json, text/plain, */*" -H "Cache-Control: no-cache" -H "Referer: http://localhost:8080/" -H "Cookie: user=vvs" -H "Connection: keep-alive" --data-binary "{""studyManager"":[{""studyProgramManager"":true,""state"":""new"",""title"":""Prof. Dr.-Ing."",""street"":""Langgässerweg 4"",""firstName"":""Jörg"",""lastName"":""Baumgart"",""sex"":""m"",""zipCode"":""64285"",""phonePrivate"":""06151 61327"",""city"":""Darmstadt"",""id"":21,""lectures"":[{""title"":""Wissenschaftliches Arbeiten III"",""shortTitle"":""wiss. Arb III""}],""name"":""Prof. Dr.-Ing. Jörg Baumgart""}],""modulePlan"":[{""name"":""WWI12SE"",""id"":1,""modules"":[{""cp"":10,""label"":""Mathe"",""id"":3,""lectures"":[{""hours"":5,""lecture"":{""title"":""Mathematik für Wirtschaftsinformatiker"",""shortTitle"":""Mathe WI""}}]},{""cp"":10,""label"":""Programmieren"",""id"":1,""lectures"":[{""hours"":4,""lecture"":{""title"":""Programmierung I"",""shortTitle"":""Programmierun""}},{""hours"":5,""lecture"":{""title"":""Fortgeschrittene Programmierung"",""shortTitle"":""PROG II""}}]},{""cp"":5,""label"":""BWL"",""id"":2,""lectures"":[{""hours"":2,""lecture"":{""title"":""Einführung in die Betriebswirtschaftslehre"",""shortTitle"":""Einf. BWL""}},{""hours"":3,""lecture"":{""title"":""Grundlagen der allgemeinen Betriebswirtschaftslehre"",""shortTitle"":""Grundlagen BW""}}]}]}],""room"":[{""name"":""255B"",""number"":""255B"",""id"":9,""course"":[]}],""name"":""wwi12SEB""}" --compressed

**Comment by LarsTi** [comment]
#189 
but tests red
