### ISSUE TITLE
Anlegen von mehreren Kursen aber gleichen Modulen

### ISSUE THREAD

**Issue by felixkam93** [WISEA12/backend#204]
![11154185_852419614828417_2045435158_o](https://cloud.githubusercontent.com/assets/5337941/7185791/6d377c54-e465-11e4-8dff-dac31fb50a67.jpg)
![11158983_852418694828509_2100806486_o](https://cloud.githubusercontent.com/assets/5337941/7185792/6d39a90c-e465-11e4-8c4a-db29972c9ad6.jpg)

Durch das Anlegen des Modul "Grundlagen Programmieren" in mehr als einem Kurs wird es in den darauf folgenden Kursen doppelt bzw dreifach etc angezeigt

**Comment by LarsTi** [comment]
#206
