### ISSUE TITLE
PDF - Vorlesungsänderungen nicht vorhanden

### ISSUE THREAD

**Issue by NessiT** [WISEA12/backend#226]
Wenn ich Vorlesungen anlege, danach ändere, sei es mit drag&drop oder über den Bearbeiten Button werden diese Änderungen nicht im PDF dargestellt

**Comment by NessiT** [comment]
Auch Änderungen bezüglich Dozent oder andere Vorlesung werden nicht geändert

**Comment by danielhartmann** [comment]
Doofe Frage, aber hast du das PDF neu geladen? Ich kann das Problem nicht reproduzieren, bei mir klappt das wunderbar. Wurd das PDF vllt irgendwo zwischengespeichert bei dir?

**Comment by NessiT** [comment]
Ich hab was geändert..den tab mit dem alten pdf geschlossen und dann über den PDF Button hat sich wieder ein neuer tab geöffnet...war aber immer ohne Änderung

**Comment by LarsTi** [comment]
fixed
@NessiT 
sag bescheid falls nicht
