### ISSUE TITLE
Raum nicht geplegt: PDF export

### ISSUE THREAD

**Issue by michischeid** [WISEA12/backend#237]
Fehler im Backendlog: Cannot read property number of null. Der Export solllte damit klar kommen, dass kein Raum gepflegt wurde

**Comment by michischeid** [comment]
genauso mit dem Dozent

**Comment by LarsTi** [comment]
Welches pdf?
Und aktuellste Version?
Am 19.04.2015 12:50 schrieb "michischeid" <notifications@github.com>:

**Comment by michischeid** [comment]
hat sich erledigt ^^
