### ISSUE TITLE
modulePlan-post errror

### ISSUE THREAD

**Issue by michischeid** [WISEA12/backend#54]
![image](https://cloud.githubusercontent.com/assets/5337937/6313553/aa78cb00-b9b2-11e4-892b-164a964f5a31.png)

id is undefined

**Comment by tarekauel** [comment]
@michischeid exact request?!

**Comment by tarekauel** [comment]
error can't be reproduced

**Comment by michischeid** [comment]
curl: curl "http://localhost:8080/api/modulePlan" -H "Pragma: no-cache" -H "Origin: http://localhost:8080" -H "Accept-Encoding: gzip, deflate" -H "Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "User-Agent: Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36" -H "Content-Type: application/json;charset=UTF-8" -H "Accept: application/json, text/plain, */*" -H "Cache-Control: no-cache" -H "Referer: http://localhost:8080/" -H "Connection: keep-alive" --data-binary "{""modules"":[]}" --compressed

**Comment by tarekauel** [comment]
curl "http://127.0.0.1:8080/api/modulePlan" -H "Pragma: no-cache" -H "Origin: http://127.0.0.1:8080" -H "Accept-Encoding: gzip, deflate" -H "Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "User-Agent: Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36" -H "Content-Type: application/json;charset=UTF-8" -H "Accept: application/json, text/plain, /" -H "Cache-Control: no-cache" -H "Referer: http://127.0.0.1:8080/" -H "Connection: keep-alive" --data-binary '{"modules":[]}' --compressed

still seems to work...
