### ISSUE TITLE
Studiengangsleiter

### ISSUE THREAD

**Issue by danielhartmann** [WISEA12/backend#60]
Studiengangsleiter wird als weitere Ressource benötigt

**Comment by danielhartmann** [comment]
Hat sich erledigt. Studiengangsleiter wird als Dozent abgebildet

**Comment by LarsTi** [comment]
not yet implemented

**Comment by fischermax** [comment]
frontend has a checkbx if a docent is "studiengangsleiter"

**Comment by LarsTi** [comment]
Will be an additional ressource (only capable of get with skip and limit and orderby)
and an additional flag in the docent.
starting to work on it now

**Comment by LarsTi** [comment]
#87 
studyProgramManager will only support a simple get (no arguments or filters or anything) due to the limited amount of belonging docents.
The answer is a list of docents!
