### ISSUE TITLE
Module post does not work

### ISSUE THREAD

**Issue by michischeid** [WISEA12/backend#63]
Error: Required fields are not filled!
required fields not documented in drive!

curl "http://localhost:8080/api/module" -H "Origin: http://localhost:8080" -H "Accept-Encoding: gzip, deflate" -H "Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "User-Agent: Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36" -H "Content-Type: application/json;charset=UTF-8" -H "Accept: application/json, text/plain, */*" -H "Referer: http://localhost:8080/" -H "Connection: keep-alive" --data-binary "{""lectures"":[],""name"":""test"",""description"":""t""}" --compressed

**Comment by tarekauel** [comment]
a module has a lable not a name and cp (credit points) are required!

**Comment by tarekauel** [comment]
curl "http://127.0.0.1:8080/api/module" -H "Origin: http://127.0.0.1:8080" -H "Accept-Encoding: gzip, deflate" -H "Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4" -H "User-Agent: Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36" -H "Content-Type: application/json;charset=UTF-8" -H "Accept: application/json, text/plain, /" -H "Referer: http://127.0.0.1:8080/" -H "Connection: keep-alive" --data-binary '{"cp": 10, "lectures":[],"label":"test","description":"t"}' --compressed
