### ISSUE TITLE
False response lectures

### ISSUE THREAD

**Issue by fischermax** [WISEA12/backend#65]
That's the response I get doing a new GET: [null,null,null,null,null,null]
That's the response after creating a new lecture: "{\"shortTitle\":\"KI\",\"title\":\"KI\"}"
I think the \ is wrong

**Comment by LarsTi** [comment]
Should be fixed in #62

**Comment by fischermax** [comment]
@LarsTi: the response of GET is [null,null,null,null,null,null] again

**Comment by LarsTi** [comment]
should be fixed in #66
