### ISSUE TITLE
PUT docent

### ISSUE THREAD

**Issue by fischermax** [WISEA12/backend#71]
Backend shoud accept id in the JSON 
At the moment this is accepted: {"firstName":"Julian","lastName":"REichwald","sex":"m","state":"new","email":"j@reichwald.de","lectures":[],"title":"Dr."}

We want to have this:
{"id":2,"firstName":"Julian","lastName":"REichwald","sex":"m","state":"new","email":"j@reichwald.de","lectures":[],"title":"Dr."}

**Comment by LarsTi** [comment]
Are you sure the docent ID Sent and the docent ID in json are equal?
Backend should already accept this.
Plesse send the used request AS attachment ;)

**Comment by fischermax** [comment]
![putdocent](https://cloud.githubusercontent.com/assets/8883870/6397472/37b0a192-bde5-11e4-84f4-5e503c16a2e9.jpg)
Yes I'm sure that the IDs are equal

**Comment by LarsTi** [comment]
#73 should fix this

**Comment by fischermax** [comment]
No it does not work; take the branch docentlecture to try on your own

**Comment by LarsTi** [comment]
not able to reproduce this issue with actual backend and actual frontend

**Comment by fischermax** [comment]
it works now.
i do not have to understand everything because yesterday I updated the backend and cleared the database.....
