### ISSUE TITLE
GETs with skip and no limit are pending

### ISSUE THREAD

**Issue by michischeid** [WISEA12/backend#78]
curl "http://localhost:8080/api/docent?orderBy=name&skip=10" -H "Accept: application/json, text/plain, */*" -H "Referer: http://localhost:8080/" -H "User-Agent: Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36" --compressed

**Comment by LarsTi** [comment]
fixed in #79 
(only for docent)
