### ISSUE TITLE
new filter for docent

### ISSUE THREAD

**Issue by michischeid** [WISEA12/backend#95]
we need a filter on the possible lectures of a docent like

http://localhost:8080/api/docent?lectureFilter="Prog1"

Is this possible? If yes ,please implement it.
Thanks.

**Comment by tarekauel** [comment]
[array Filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)

I guess you have all the information already, haven't you? So maybe it's much simpler for you to use a js function

**Comment by michischeid** [comment]
where is the reason o f sending all data over the network for filtering it at the frontend? It is not needed at the docent-screen but for the event-screen

**Comment by LarsTi** [comment]
#99 
GET:
/api/docent?lecture="lecture.shortTitle"

**Comment by michischeid** [comment]
filter: /api/docent?lecture="lecture.shortTitle" was not specified in drive doc "Schnittstelle". I did it now.
